name: Docker Caching
description: Cache a docker image

inputs:
  dockerdir:
    required: true
    type: string
  imagename:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Check for cached docker image
      id: cached-docker
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: dockerimage-${{ hashFiles(format('{0}/**', inputs.dockerdir)) }}.tar
        key: ${{ runner.os }}-dockerimagetar-${{ hashFiles(format('{0}/**', inputs.dockerdir)) }}

    - name: Load docker image
      if: steps.cached-docker.outputs.cache-hit == 'true'
      run: docker load --input dockerimage-${{ hashFiles(format('{0}/**', inputs.dockerdir)) }}.tar
      shell: bash

    - name: Build/label docker image
      run: docker build -t ${{ inputs.imagename }} ${{ inputs.dockerdir }} --cache-from ${{ inputs.imagename }}:latest
      shell: bash

    - name: Save docker image
      if: steps.cached-docker.outputs.cache-hit != 'true'
      run: docker save --output dockerimage-${{ hashFiles(format('{0}/**', inputs.dockerdir)) }}.tar ${{ inputs.imagename }}:latest $(docker history -q ${{ inputs.imagename }}:latest | grep -v missing)
      shell: bash
